export const requirements = [
  "Natural Science and Mathematics",
  "Quantitative Reasoning",
  "First year course",
  "Natural Science and Mathematics Learning Goals",
  "Writing Level 2",
  "Arts and Humanities",
  "Foreign Language",
  "Lab Science",
  "Community Engaged Learning",
  "Social Science",
  "Global Connections",
  "Diversity in the U.S.",
  "Race, Power and Inequality",
  "Social Science Learning Goals",
  "Arts and Humanities Learning Goals",
  "Residential College",
  "Environmental Connections",
  "Integrated Perspectives",
  "Nature, People and Justice",
  "Foundation Seminar",
  "Writing Level 1",
  "Community Based Learning"
]