export const requirements = [
  "Natural Science and Mathematics",
  "Quantitative Reasoning",
  "First year course",
  "Natural Science and Mathematics Learning Goals",
  "Arts and Humanities",
  "Foreign Language",
  "Arts and Humanities Learning Goals",
  "Writing Level 2",
  "Lab Science",
  "Social Science",
  "Social Science Learning Goals",
  "Global Connections",
  "Foundation Seminar",
  "World Building",
  "Global Mosaic",
  "Writing Level 1",
  "Community Engaged Learning",
  "Environmental Connections",
  "Green Futures",
  "Myself & Others",
  "Words We Live",
  "Residential College",
  "Languages & Cultures Res Coll",
  "Agents of Change",
  "Creative Dimensions",
  "Nature, People and Justice",
  "The Real & The Invented World",
  "Discovery Residential College",
  "Community Based Learning",
  "Society & Tech Res College",
  "Diversity in the U.S.",
  "Race, Power and Inequality",
  "Global Residential College",
  "Arts Residential College",
  "Integrated Perspectives",
  "Environmental Res College",
  "Social Justice Res College",
  "Humanities Residential College",
  "Food Residential College"
]