export const requirements = [
  "Natural Science and Mathematics",
  "Quantitative Reasoning",
  "First year course",
  "Natural Science and Mathematics Learning Goals",
  "Writing Level 2",
  "Arts and Humanities Learning Goals",
  "Arts and Humanities",
  "Lab Science",
  "Foreign Language",
  "Social Science",
  "Global Connections",
  "Diversity in the U.S.",
  "Race, Power and Inequality",
  "Social Science Learning Goals",
  "Community Engaged Learning",
  "Foundation Seminar",
  "Residential College",
  "Writing Level 1",
  "Environmental Connections",
  "Nature, People and Justice",
  "Integrated Perspectives"
]